[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DecisionMaking = "2dd64264-fe6c-11e8-3224-e53a2d8a0f9e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EnhancedGJK = "3d39a06a-b57e-5769-b499-4d62b23c243f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LibSpatialIndex = "dc06f288-cecb-5e6a-a934-a4be3681a024"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
MultiAgentFactory = "e1db0f5e-033c-11e9-27d1-35b020e889c9"
MultiFidelityBehaviorPrediction = "34184550-fe6c-11e8-30fe-716b78cf3674"
NGSIM = "5023ee20-fe71-11e8-1b30-2df05f2ba055"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
Roadways = "20568c56-94ac-525a-8f38-92363f7fd59c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"
